#!/bin/bash
[[ "$1" == "intermediate" ]] && exit 0
set -ex

binary="presto_metrico"
source_path="$(readlink -f "$(dirname "${BASH_SOURCE[0]}")/..")"
if [[ -d /artifacts ]] ; then
  artifacts_path="/artifacts"
else
  artifacts_path="${source_path}"
fi

godep go build -o "${artifacts_path}/${binary}"
